### ISSUE TITLE
documentation for software isnt complet

### ISSUE THREAD

**Issue by Xamrias** [bbz-hft-software-engineering/Slush-YV-fikation#31]
# Bug

## Short
Software no longer corresponds with Structugramm 

## Description

- Divers
-

## Definition of Done/Solution:

- Software and Documentation correspond
- 

## StoryPoint:

__3__

**Comment by Mobileplayers** [comment]
updated software structograms and added comments to software.
Added aditional structogram for function FlankHandler.
